module.exports = {
  ALARM_CAUSES: {
    CONFIRMED: 17669,
    FALSE_ALARM: 17670,
    OTHERS: 17671,
    TRIGGERED_BY_CLIENT: 17672,
    TRIGGERED_BY_TECHNICIAN: 17673
  },

  OCCURRENCE_STATUS: {
    OPEN: 'OPEN',
    STARTED: 'STARTED',
    CLOSED: 'CLOSED'
  }
};
